version: "3.8"
services:
  php:
    build:
      context: .
      args:
        PHP_MODE: production
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      - redis-master
      - redis-slave

  redis-master:
    image: bitnami/redis:latest
    restart: unless-stopped
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_REPLICATION_MODE: master

  redis-slave:
    image: bitnami/redis:latest
    restart: unless-stopped
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: redis-master
      REDIS_MASTER_PORT_NUMBER: 6379
    depends_on:
      - redis-master
